### ISSUE TITLE
Viewing two responses of type: object leads to a visual bug where only the first response object is displayed

### ISSUE THREAD

**Issue by lizzynibali** [readmeio/api-explorer#1042]
Hello all!

I encountered a small bug in displaying response objects in the API explorer that could cause confusion for anyone trying to understand my API.

### Steps to reproduce
1. write up an OpenApi spec that has two responses that are both objects and a third response that is a simple description (Ex. a text response). For example:

```
openapi: 3.0.3
info:
  version: '1'
  title: 'Bug Example API'
  contact:
    email: help@helper.io
  description: a description
servers:
  - description: Example Server
    url: https://example.server.com
paths:
  /example:
    post:
      operationId: samplePath
      description: a description
      requestBody:
        sampleBody:
          description: sample description
          content:
            application/json:
              schema:
                sampleParameter:
                  description: parameter description
                  type: string
      responses:
        "200":
          description: 200 response
          content:
            x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  id:
                    description: id description
                    type: string
                    format: uuid
                  quantity:
                    description: quantity description
                    type: integer
        "2XX":
          description: 200 response
          content:
            x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  name:
                    description: name description
                    type: string
                  gift:
                    description: gift description
                    type: string
        "400":
          description: 200 response
```

2. Upload path with two object responses to Readme
3. View the request in the API Explorer
4. Select 200 response, see 200 response object and 200 description
5. Select 2XX response, see 200 response object and 2XX description
6. Select 400 response, see 400 response description, no object information displayed
7. Select 2XX response, see 2XX response object and 2XX description
8. Select 200 response, see 2XX response object and 200 description

Note that this behavior also happens if you fully define the 400 response, so:
```
    '400':
      description: 400 description
      content:
        text/plain:
          schema:
            type: string
```

would result in this behavior:

4. Select 200 response, see 200 response object and 200 description
5. Select 2XX response, see 200 response object and 2XX description
6. Select 400 response, see 200 response object and 400 description
7. Select 2XX response, see 200 response object and 2XX description
8. Select 200 response, see 200 response object and 200 description

my guess is we only ever see the 200 response object because there was no "blank" schema to clear out the visual bug.

### Expected Behavior:
(with the same yaml as above)
4. Select 200 response, see 200 response object and description
5. **Select 2XX response, see 2XX response object and description**
6. Select 400 response, see 400 response description only

### Impact:

When my users are viewing my API, seeing an incorrect object alongside the correct description could be confusing especially if it's their first time encountering our API. This behavior also makes things more difficult to troubleshoot any issues while writing my OpenApi spec and validating it through Readme.

Please let me know if I can provide more information, I appreciate you all taking a look!

**Comment by fabrilallo** [comment]
Hello! Any update for this issue? thx

**Comment by erunion** [comment]
@fabrilallo Not yet unfortunately. Hoping to get to this this coming week.

**Comment by erunion** [comment]
Able to replicate this, looking into it now! We should be able to have fix out in next weeks general release.

**Comment by erunion** [comment]
Fixed in https://github.com/readmeio/api-explorer/pull/1081

**Comment by lizzynibali** [comment]
@erunion thank you so much for taking a look at this! I know it's a small thing and I appreciate your time
