### ISSUE TITLE
Query param type error

### ISSUE THREAD

**Issue by gkoberger** [readmeio/api-explorer#110]
When using the “Object/Hash” query param type, after saving and viewing the docs I get the following error on the page:

![image](https://user-images.githubusercontent.com/381393/38112450-cdec8150-3356-11e8-883d-dc9e9c1b11a0.png)

**Comment by domharrington** [comment]
This looks like the schema is missing a `properties` object. I dont think i've seen this but it would need investigation to see if it can be reproduced.

**Comment by domharrington** [comment]
This is now fixed. See "object without `properties`" here: https://preview.readme.io/?selected=swagger-files%2Ftypes.json
