### ISSUE TITLE
File type param

### ISSUE THREAD

**Issue by gkoberger** [readmeio/api-explorer#111]
Error when using a File as a type

![image](https://user-images.githubusercontent.com/381393/38112474-e88fa190-3356-11e8-9e98-f8fc70fe2bb7.png)

**Comment by uppal101** [comment]
It looks like OpenAPI 3.0 doesn't accept file as a type. I also believe that the new api explorer converts swagger to the latest OpenAPI spec https://swagger.io/docs/specification/data-models/data-types/#file

**Comment by uppal101** [comment]
OAS 3 does not have type file it should be specified as string
https://swagger.io/docs/specification/data-models/data-types/#file

**Comment by domharrington** [comment]
Now we render file inputs, but we cannot currently upload multipart forms. This is another issue.
