### ISSUE TITLE
Anchor tabs not working

### ISSUE THREAD

**Issue by gkoberger** [readmeio/api-explorer#112]
Non-header anchor tags have stopped working. For instance, the following link goes nowhere: https://developers.trello.com/v1.0/reference#section-serviceproviderconfig. I’d thought this was something that was working, but I could be wrong.

**Comment by uppal101** [comment]
It seems to be working from what I can tell https://developers.trello.com/v1.0/reference#section-excluded-action-types

**Comment by nadalfederer** [comment]
I've tried to find out where is `lazy-rendering` located in a project, but unsuccessful. Can you point out where it has done or is it not important to this task?

**Comment by domharrington** [comment]
Look for react-waypoint and the Waypoint component.

**Comment by domharrington** [comment]
@nadalfederer please do not pick this one up, @mjcuva is going to be working on it.

**Comment by erunion** [comment]
This is no longer an issue.
