### ISSUE TITLE
Allow clipboard copy of the response body

### ISSUE THREAD

**Issue by jordanmnunez** [readmeio/api-explorer#1188]
Is there a reason `enableClipboard` is set to `false`?
https://github.com/readmeio/api-explorer/blob/next/packages/api-explorer/src/ResponseBody.jsx#L24

We have a lot of requests to be able to copy the results from the api explorer. It seems like setting this to `true` would solve this problem for us and I cannot think of a downside to having it there.

**Comment by erunion** [comment]
👋  &nbsp;I wasn't sure why we had this disabled either but after playing with it enabled we're going to leave it off for now as the UI it adds isn't great.

https://user-images.githubusercontent.com/33762/108268204-0cf25680-7121-11eb-8c7c-138f6a3c8489.mov

We're working on a complete redesign of our API Explorer and Reference guides (targeting a Q2 release) and will instead make sure that response copying functionality is present there instead.

**Comment by jordanmnunez** [comment]
Thanks for looking into my issue!

We often return very large and deeply nested datasets. This makes viewing/obtaining the response an absolute pain in the current viewer. 

I think including the clipboard is net positive. While it may not be the best ux, it solves a very real problem.

If this was my product, I would ship it without question in favor of the short term gain. The new tool you are building is an added assurance that "we will have a better solution in a few month". With that said, it is not my product and therefore not my decision.

Thanks again for looking into this so promptly.
