### ISSUE TITLE
Can we pass custom code snippets in api-explorer right pane?

### ISSUE THREAD

**Issue by pkvenu** [readmeio/api-explorer#121]
Is there a way to pass custom code snippets into api-explorer. I tried adding the examples code block in swagger spec, but it did not affect the right sidebar.

```
    "/restapi/": {
      "get": {
        "tags": [
          "API Info"
        ],
        "summary": "Get API Versions",
        "description": "Returns current API version(s) and server info.",
        "operationId": "getAllVersions",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetVersionsResponse"
            }
          }
        },
        },
      "examples": {
        "codes": [{
          "language": "javascript",
          "code": "console.log(1);"
        }]
      }
    },
```

Also is it possible to display the description from the swagger spec in the explorer ?

**Comment by domharrington** [comment]
Hey! Sorry for the late reply.

You can do this using responses. Here's a link to the demo app showing this:
https://preview.readme.io/?selected=swagger-files%2Fexamples.json

Here's the relevant part of the swagger file: https://github.com/readmeio/api-explorer/blob/3ad36f9a85db42034c5e0568c3f10445d8d997a6/example/swagger-files/examples.json#L16
