### ISSUE TITLE
API explorer can't resolve this yaml file.

### ISSUE THREAD

**Issue by hessaam** [readmeio/api-explorer#1218]
I got this swagger file to api-explorer and it can't resolve it.
[github.txt](https://github.com/readmeio/api-explorer/files/6101359/github.txt)
This is the mentioned error.
![image](https://user-images.githubusercontent.com/50245527/110322651-b2199400-8028-11eb-92c1-be2db8c73a56.png)
@erunion

**Comment by erunion** [comment]
I'm having trouble replicating this. What's the error that's showing up in your browser console?

**Comment by SeyyedHesam** [comment]
@erunion 
TutorialModal(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

**Comment by erunion** [comment]
Where are you receiving this error? On a ReadMe project, or running this codebase locally?

**Comment by SeyyedHesam** [comment]
@erunion 
On the api-explorer project

**Comment by erunion** [comment]
Ok, unfortunately this codebase can't really be utilized outside of ReadMe as it's pretty tightly integrated into our UI library (as shown by the TutorialModal error you're getting). Sorry :(

**Comment by SeyyedHesam** [comment]
@erunion 
Please look at this [https://preview.readme.io/reference/?url=](URL).

**Comment by erunion** [comment]
I've just fixed this in https://github.com/readmeio/api-explorer/commit/dc2a47145c3c1238ffebd4f6ce20c61445834fd2 and deployed the fix to https://preview.readme.io/reference/. Thanks for the heads up.

**Comment by SeyyedHesam** [comment]
Thanks!
