### ISSUE TITLE
How to run it in Windows?

### ISSUE THREAD

**Issue by LuoPQ** [readmeio/api-explorer#122]
Does anyone know how to run it in Windows

**Comment by domharrington** [comment]
Hey!

There's no reason why this module shouldn't run in windows. What browser are you attempting? Does this page not work? https://readmeio.github.io/api-explorer/

**Comment by domharrington** [comment]
Can you try running `npx lerna bootstrap` in the root?

**Comment by LuoPQ** [comment]
@domharrington Yes, I've tried it, still got errors

**Comment by domharrington** [comment]
What errors did you get?

**Comment by nadalfederer** [comment]
I've run it on windows10 as it said in an instruction, everything is working fine.
![image](https://user-images.githubusercontent.com/6043510/48647098-fc138180-e9fb-11e8-9a42-dacd849f6a95.png)
