### ISSUE TITLE
Support hidden endpoints

### ISSUE THREAD

**Issue by piersmacdonald** [readmeio/api-explorer#128]
Loving this feature, we're looking to kick our documentation up a notch. Something that would be great is the ability to select which endpoints are visible.

For example our app autogenerates it's swagger documentation, that would be the easiest to sync with readme.io. However I don't want customers to see our `/healthcheck` endpoints or admin ones. 

I'm not sure what the implementation looks like but it would be great to have a way to selectively display paths/models etc.

Also, when is open api 3.0 upload support coming?

**Comment by piersmacdonald** [comment]
Ugh, never mind. I thought the 'eye' functionality did something else. Turned out I just needed to refresh my page.

I'm sorry.

Still: poke poke on OAS 3.0

**Comment by gkoberger** [comment]
@piersmacdonald OAS 3.0 is coming by the end of the month :)

**Comment by domharrington** [comment]
@piersmacdonald sorry for the late reply on this. OAS 3 is now supported in ReadMe.
