### ISSUE TITLE
RJSF widget (`<StringField>`) error thrown when scrolling through `apacta.com` JSON 

### ISSUE THREAD

**Issue by achalvs** [readmeio/api-explorer#129]
<img width="1680" alt="screen shot 2018-07-30 at 5 23 26 pm" src="https://user-images.githubusercontent.com/1936207/43482582-f51e825a-94bd-11e8-9f47-5bf198ff4eb0.png">

RJSF throws an error when scrolling past the `Edit expense line` endpoint in the `apacta.com` example. Has to do with the `<StringField>` component. It refreshes the page after the first thrown error, and displays a blank screen after the second time it's thrown.

Steps to reproduce:

1. `> npm start`
2. Navigate to `localhost:9966`
3. Scroll down quickly past `Edit expense line` endpoint with browser's console open.

Link to docs on `localhost`: http://localhost:9966/?selected=https%3A%2F%2Fapi.apis.guru%2Fv2%2Fspecs%2Fapacta.com%2F0.0.1%2Fswagger.json

**Comment by domharrington** [comment]
Can you link to the localhost URL with the apacta swagger file?

**Comment by achalvs** [comment]
added to issue above but not sure if you got a notif for update. here it is: http://localhost:9966/?selected=https%3A%2F%2Fapi.apis.guru%2Fv2%2Fspecs%2Fapacta.com%2F0.0.1%2Fswagger.json

**Comment by domharrington** [comment]
From the error message in the console it looks as though they had the following:

```
{ type: string, format: 'Y-m-d' }
```

This is not supported in OAS: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types

This will hopefully render nicer now due to the error boundaries as well.
