### ISSUE TITLE
Why put response body onto "REQUEST DATA" section

### ISSUE THREAD

**Issue by LuoPQ** [readmeio/api-explorer#135]
In this file "ResponseMeta.jsx", Could you please tell me why put the responseBody on the "Request Data", it looks confusing

      <Meta label="URL">
        <div>{result.url}</div>
      </Meta>

      <Meta label="Request Headers">
        <pre>{result.requestHeaders.join('\n')}</pre>
      </Meta>

      <Meta label="Request Data">
        <pre>{JSON.stringify(result.responseBody)}</pre>
      </Meta>

      <Meta label="Status">
        <span className="httpstatus">
          <IconStatus status={result.status} />
        </span>
      </Meta>

      <Meta label="Response Headers">
        <pre>{result.responseHeaders.join('\n')}</pre>
      </Meta>

**Comment by domharrington** [comment]
Hey @LuoPQ, that definitely looks like a bug. I've just committed a fix which will be deployed to readme within the next day or so. Thanks for reporting.

**Comment by LuoPQ** [comment]
@domharrington  I saw your solution, it only displays post data, sometimes we have query parameters, doesn't show that
