### ISSUE TITLE
parameter bug, root cause: the value of boolean parameter is false

### ISSUE THREAD

**Issue by LuoPQ** [readmeio/api-explorer#149]
1. If we define "false" as a default value for boolean parameter, it can't display in the generated form, because the following code in **parameters-to-json-schema.js**:
`if (current.schema.default) schema.default = current.schema.default;`

2. If we pass a "false" to parameter for calling an API, the "false" can not be passed, due to the following in **oas-to-har.js**:
```
function formatter(values, param, type, onlyIfExists) {
  if (values[type][param.name]){
    return format.value(values[type][param.name]); 
  }
  ...
}

if (queryStrings && queryStrings.length) {
    queryStrings.forEach(queryString => {
      const value = formatter(formData, queryString, 'query', true);
      if (value) return;
    }
   ....
}
```

**Comment by domharrington** [comment]
Hey @LuoPQ, sorry about that, that looks like a bug. The correct implementation would be to check for `typeof a === 'undefined'` to catch those falsy values.

I'm happy to accept a PR for the fix if you're willing to work on it!
