### ISSUE TITLE
extract react-openapi-form

### ISSUE THREAD

**Issue by jbadeau** [readmeio/api-explorer#169]
Hi,

I am currently looking into generating forms from openapi. It would be really cool if you could extract out an npm module that contains only the form generation  code.

extract react-openapi-form would contain something like:

- form-components/
- ArrayField.jsx
- BaseInput.jsx
- DescriptionField.jsx
- FileWidget.jsx
- index.jsx
- SchemaField.jsx
- SelectWidget.jsx
- TextareaWidget.jsx
- lib/
- find-schema-definition.js
- get-path.js
- get-path-operation.js
- get-schema.js
- index.jsx
- Oas.js
- parameters-to-json-schema.js

What do you think?

**Comment by domharrington** [comment]
If you want to extract it out to a separate folder within the packages/ folder of this repo, feel free to send a PR! I'm not against it in principle; it would be a lot of work for us to do on our own without your help.
