### ISSUE TITLE
Explorer doesn't render when the object reference is empty

### ISSUE THREAD

**Issue by ShamsUlAzeem** [readmeio/api-explorer#174]
Look at the following code: 

```
/endpoints/{deploymentName}/datavec/{transformName}/{versionName}/transformprocess:
    post:
      operationId: transformprocess_post
      summary: Sets the deployed (CSV or Image) transform process through the provided JSON string
      tags:
      - Transform
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: deploymentName
        in: path
        description: Name of the deployment group
        required: true
        type: string
      - name: versionName
        in: path
        description: Version name of the endpoint. The default value is "default"
        required: true
        default: default
        type: string
      - name: transformName
        in: path
        description: ID or name of the deployed transform
        required: true
        type: string
      - in: body
        name: TransformProcess
        description: The transform process to set
        schema:
          type: object
      responses:
        200:
          description: transform process set successfully
          schema:
            type: object
        500:
          description: internal server error
```

It gives the following output in the api-explorer:

![capture](https://user-images.githubusercontent.com/17789400/48840591-ef52ad00-edb0-11e8-84d7-bd7e6d3a7c23.PNG)

By saying: `Invalid root object field configuration:Cannot convert undefined or null to object.`

**Proposal**
Maybe a better way to deal with this case is to show nothing under the `BODY PARAMS` header.

**Comment by domharrington** [comment]
Hey!

The issue here is because you have defined:

```
schema:
  type: object
```

But you have not defined any properties for this object. If you don't need any body params, remove this whole block:

```
- in: body
  name: TransformProcess
  description: The transform process to set
  schema:
    type: object
```

If you do have properties, define them within the schema. If you don't then the correct thing to do would be to define `additionalProperties`. See https://json-schema.org/understanding-json-schema/reference/object.html for more details. However, we do not currently support additionalProperties.

**Comment by ShamsUlAzeem** [comment]
@domharrington I see. It used to work before with the previous api-explorer. Maybe we should add this kind of error notification in the linter that's used with validating the swagger files. If that's not possible then it would be useful to update the new explorer because a lot of people might run into this issue. Sometimes the request objects are too complex to define every property.

**Comment by domharrington** [comment]
What would you expect the form to render if the object properties haven't been defined?

**Comment by ShamsUlAzeem** [comment]
@domharrington. Just show the error message. That's useful enough. You can see in the picture I posted above that the rendered page contains a really long JSON string underneath the error message. That won't be necessary.

**Comment by domharrington** [comment]
See here for more details: https://github.com/readmeio/api-explorer/issues/199
