### ISSUE TITLE
Support for `application/vnd.api+json`

### ISSUE THREAD

**Issue by sjkaliski** [readmeio/api-explorer#188]
For APIs that return `Content-Type: application/vnd.api+json`, I'm curious if the definition of [`isJson`](https://github.com/readmeio/api-explorer/blob/8d98ce0bf35074d06750d88d8fd581f68f5b326a/packages/api-explorer/src/lib/parse-response.js#L14) can be expanded to include that content-type.

Happy to help contribute and work on this!

**Comment by domharrington** [comment]
Hey! Sorry for the late reply on this, i'd happily accept a PR!

You should be able to write a test for this, much like this one:
https://github.com/readmeio/api-explorer/blob/8d98ce0bf35074d06750d88d8fd581f68f5b326a/packages/api-explorer/__tests__/lib/parse-response.test.js#L173-L175

There may be other places in the code where we've hardcoded application/json though, but feel free to send a PR fixing those too.
