### ISSUE TITLE
Fix style issue when "array of objects" contains another object

### ISSUE THREAD

**Issue by domharrington** [readmeio/api-explorer#193]
Replace this object here: https://github.com/readmeio/api-explorer/blob/master/example/swagger-files/types.json#L180

With this:

```json
"array of objects": {
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "format": "int64"
      },
      "name": {
        "type": "string"
      },
      "object": {
        "type": "object",
        "properties": {
          "a": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

This incorrectly outputs an "array of objects" label around the inner object:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/848223/53594638-24109600-3b50-11e9-8203-8081f20a5621.png">

It should just display "object" in the :after element.

**Comment by nadalfederer** [comment]
@domharrington Is this a place to fix this bug 
https://github.com/readmeio/api-explorer/blob/master/packages/api-explorer/src/form-components/ArrayField.jsx?

**Comment by domharrington** [comment]
Any more details on what's causing this? Can we use CSS to fix it?
