### ISSUE TITLE
Automatically default `type` to object if no type set

### ISSUE THREAD

**Issue by domharrington** [readmeio/api-explorer#200]
This is kinda the other side of this issue: #199.

Some people pass `properties` but do not tell us that it's an object. We should default `type` to `object` if they've not provided one.

This is what happens if you remove `type: object` from a JSON schema:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/848223/55521507-d814ad80-5635-11e9-9cd6-678319b78b49.png">

**Comment by erunion** [comment]
Per https://github.com/readmeio/api-explorer/pull/206#issuecomment-520520127 this is no longer a bug.

**Comment by domharrington** [comment]
We fixed this upstream: https://github.com/mozilla-services/react-jsonschema-form/pull/1292
