### ISSUE TITLE
Add support for common parameters

### ISSUE THREAD

**Issue by domharrington** [readmeio/api-explorer#210]
We currently do not support common parameters. (https://swagger.io/docs/specification/describing-parameters/#common-parameters)

Workaround is to add them inline for each endpoint for now

Taken from canny: https://readmeio.canny.io/feature-requests/p/add-support-for-common-parameters

----------

Normally you add parameters in Open API like so:

```js
{
  paths: {
    '/path': {
      get: {
        parameters: []
      }
    }
  }
}
```

But it is supported for you to define them like this:

```js
{
  paths: {
    '/path': {
      parameters: []
      get: {
      }
    }
  }
}
```

We should add support for these.

**Comment by domharrington** [comment]
@nadalfederer can you take a look at this?

**Comment by nadalfederer** [comment]
sure
