### ISSUE TITLE
uglifyjs-webpack-plugin is breaking the production output!

### ISSUE THREAD

**Issue by domharrington** [readmeio/api-explorer#213]
Over in #204 we fixed the following case:

```
"object without `properties`": {
  "type": "object"
}
```

This works great in the demo app:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/848223/57001493-c7405480-6b6d-11e9-9590-bb2d297b918d.png">

http://localhost:9966/?selected=swagger-files%2Ftypes.json

But when it's compiled down to production using `npm run build` it breaks!

<img width="742" alt="image" src="https://user-images.githubusercontent.com/848223/57001505-d7583400-6b6d-11e9-81a1-3bfcf9b85e7d.png">

https://preview.readme.io/?selected=swagger-files%2Ftypes.json

The upstream fix was here: https://github.com/mozilla-services/react-jsonschema-form/blob/f9d4c63cac24146e522528d33eb04f465464e052/src/components/fields/ObjectField.js#L201

It appears as though that's getting compiled away by `uglify-es` and `uglifyjs-webpack-plugin`: https://github.com/readmeio/api-explorer/blob/b32a2146737c11813bd1b222a137de61854414b3/package.json#L43-L44

<img width="452" alt="image" src="https://user-images.githubusercontent.com/848223/57001544-18e8df00-6b6e-11e9-8a42-77a828be60f9.png">

Can you try and investigate bumping this dependency and see if it works? Version 2 of `uglifyjs-webpack-plugin` looks like they removed `uglify-es` and switched back to `uglify-js`. https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/CHANGELOG.md#breaking-changes 

They recommend using https://github.com/webpack-contrib/terser-webpack-plugin.

**Comment by domharrington** [comment]
@nadalfederer can you take a look at this?

**Comment by nadalfederer** [comment]
sure

**Comment by nadalfederer** [comment]
I've not been able to reproduce this, I run `npm run build` after that there is a dist folder has been created but when I open example/dist/index.html in browser I'm not seeing this error. What am I doing wrong?

**Comment by domharrington** [comment]
Huh that's very strange. I also cannot reproduce locally, but the issue is definitely still present here: https://preview.readme.io/?selected=swagger-files%2Ftypes.json

The string to search for in the bundled output is this `.properties||{}`. In the local demo-bundle.js, there's this one `(C.properties||{})` which is missing from here: https://preview.readme.io/demo-bundle.js

**Comment by nadalfederer** [comment]
![image](https://user-images.githubusercontent.com/6043510/57581663-42d1c800-74c3-11e9-88a2-3ac274d3f100.png)
The bug is gone here. Did something happen there? Also `(C.properties||{})` exists here https://preview.readme.io/demo-bundle.js.

**Comment by nadalfederer** [comment]
@domharrington Hi, is this bug still relevant? About other PRs, they are ready. Have I done something wrong or you are busy?

**Comment by domharrington** [comment]
Hey Vlad! You've done nothing wrong, I'm just very busy. I will try to review them in the next few days :)

**Comment by erunion** [comment]
This appears to no longer be an issue.

![Screen Shot 2019-08-07 at 10 34 56 AM](https://user-images.githubusercontent.com/33762/62644477-0addf380-b8ff-11e9-8d4f-bf0fd22f56a4.png)
