### ISSUE TITLE
Is the markdown parser extensible?

### ISSUE THREAD

**Issue by byrnereese** [readmeio/api-explorer#215]
I utilize a number of python markdown extensions that make publishing my documentation much easier, and gives me controls to create more complex DOM structures from markdown. Specifically: https://python-markdown.github.io/extensions/admonition/

Which converts:
```
!!! note
    You should note that the title will be automatically capitalized.
```

Into:

```
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>You should note that the title will be automatically capitalized.</p>
</div>
```

Is there a way this could be implemented within api-explorer?

**Comment by domharrington** [comment]
Hey @byrnereese... 

What I would recommend for you is to provide us with a HTML block!

You can do this using the following:

```
[block:html]
{
  "html": "<div>Custom HTML</div>"
}
[/block]
```

This will then be rendered in your readme project. You can also of course just send us HTML

```
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>You should note that the title will be automatically capitalized.</p>
</div>
```

But I cannot 100% guarantee that our markdown parser won't strip this out. You should be safe using the Block method above ^^

Dom

**Comment by domharrington** [comment]
On further investigation, we strip out classes from raw HTML that you paste into markdown:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/848223/58138841-e1110c80-7bec-11e9-853c-f1d18913f4af.png">

Using a block works:

```
[block:html]
{
  "html": "<div class=\"admonition note\"><p class=\"admonition-title\">Note</p><p>You should note that the title will be automatically capitalized.</p></div>"
}
[/block]
```

<img width="496" alt="image" src="https://user-images.githubusercontent.com/848223/58138882-0d2c8d80-7bed-11e9-9bb4-69cefcc5ac13.png">

**Comment by byrnereese** [comment]
So what I am understanding is that there is no way to extend the markdown parser. That would be an awesome feature if ever there was one. :)
