### ISSUE TITLE
Parse-magic-blocks

### ISSUE THREAD

**Issue by uppal101** [readmeio/api-explorer#26]
Look into if addTextareas is used anywhere

https://github.com/readmeio/api-explorer/blob/4233d9b19ce28717ab41d4b74824ace84de8edd8/packages/api-explorer-ui/src/lib/parse-magic-blocks.js#L3

The only place addTextareas is seen is in legacy-stuff/magic/magictext.js but we basically copied that functionality into parse-magic blocks

**Comment by domharrington** [comment]
This is only used in the dash. Nothing needs to happen for this for now.
