### ISSUE TITLE
Should we surface string formats?

### ISSUE THREAD

**Issue by erunion** [readmeio/api-explorer#262]
Currently if a `string` has a special format like `date`, `url`, `binary`, etc we only render it in the UI as a `string`. 

![Screen Shot 2019-08-07 at 5 00 58 PM](https://user-images.githubusercontent.com/33762/62665648-f7e61600-b934-11e9-948d-97313e6661fc.png)

It might give some more clarity to the person reading the docs what kind of string they should be supplying (especially if an example or default isn't being documented by the API owner).

Only real downside or hurdle I see to doing this is that our current css in `api-explorer.css` will need a major rewrite to support something this dynamic. Or maybe we should take this as an opportunity to redesign how we represent those formats entirely?

**Comment by domharrington** [comment]
Would it be possible for us to do this in CSS? Similar to how we do the number formats?

https://github.com/readmeio/api-explorer/blob/70909b5ac656d367425bbc208296fede5a2f1188/packages/api-explorer/api-explorer.css#L424

https://github.com/readmeio/api-explorer/blob/70909b5ac656d367425bbc208296fede5a2f1188/packages/api-explorer/src/form-components/SchemaField.jsx#L60

**Comment by rafegoldberg** [comment]
@domharrington that would work, but wouldn't you have to manually upkeep the styles/classes for every variation of type combinations?

**Comment by erunion** [comment]
We don't currently keep the `format` anywhere in the view, so it would require a little bit of work to `SchemaField`, but yeah I'm mostly concerned about creating another large list of CSS overrides to maintain like we already have in there.

**Comment by domharrington** [comment]
Yeah agree. I'm open to other suggestions for sure but that seemed like the quickest win for now!
