### ISSUE TITLE
Do we need `categoriesAsDropdown` in marked.js?

### ISSUE THREAD

**Issue by domharrington** [readmeio/api-explorer#28]
I'm removing it for now, but we may wanna bring it back in future. It's the only dependency that our markdown renderer has on the request object.

https://github.com/readmeio/api-explorer/blob/7f0cbc0fd34e5332826486deafc84545f16edb7c/packages/api-explorer/src/lib/markdown/renderer.js#L72-L75

I'm gunna bring over the `correctnewlines` option though and will have it passed in as a top level option to the `ApiExplorer` component.

**Comment by domharrington** [comment]
Only a handful of projects have this option turned on. This can wait until one of those moves to the new explorer.

**Comment by erunion** [comment]
This code no longer exists anywhere.
