### ISSUE TITLE
Need to figure out what to do about angular links in markdown

### ISSUE THREAD

**Issue by domharrington** [readmeio/api-explorer#29]
https://github.com/readmeio/api-explorer/blob/9639c0742a8082328eadd63459b1c373476c11ed/packages/api-explorer-ui/src/lib/marked.js#L80

**Comment by domharrington** [comment]
See the problem here (click this link "Getting Started with swagger-pet-store1"):

This is using the old api explorer:
https://swagger-pet-store1.readme.io/v1.0/reference#updatepet

It works because angular and pjax hijack the link and render the new page content.

This does not work:
https://swagger-pet-store1.readme.io/v1.0/reference?newApiExplorer=true#updatepet

I think we need to remove everything to do with uiSref from the markdown and just use normal hyperlinks in their place.

- [ ] https://github.com/readmeio/api-explorer/blob/9b4b01c76d9b44f4c70d99abc06c16c8ece0226b/packages/api-explorer/src/lib/markdown/renderer.js#L81 should be replaced with `/blog/:blog`
- [ ] https://github.com/readmeio/api-explorer/blob/9b4b01c76d9b44f4c70d99abc06c16c8ece0226b/packages/api-explorer/src/lib/markdown/renderer.js#L64 should be replaced with `/doc/:doc`
- [ ] https://github.com/readmeio/api-explorer/blob/9b4b01c76d9b44f4c70d99abc06c16c8ece0226b/packages/api-explorer/src/lib/markdown/renderer.js#L87 should be replaced with `/page/:custompage`

**Comment by domharrington** [comment]
Right now our markdown renderer is outputting the following:

From this:
```
[Getting Started with swagger-pet-store1](doc:getting-started)
```

To this:

```
<a ui-sref="docs.show({'doc': 'getting-started'})">
```

We need to change it to a regular link, so it outputs:

```
<a href="/doc/getting-started">
```

**Comment by uppal101** [comment]
#103
