### ISSUE TITLE
Code block converts to tab

### ISSUE THREAD

**Issue by jrschumacher** [readmeio/api-explorer#616]
The following markdown will convert to a tabbed code block:

_Disregard the `\`, using to prevent the code block parser_
```
\```
Some code here
\```
Some text here
\```
Some code here
\```
```

While in Github, Slack, and other renderers I've used it gets parsed like:

```
Some code here
```
Some text here
```
Some code here
```

**Comment by rafegoldberg** [comment]
Standard markdown requires you to add a line break in between sequential code blocks. We take advantage of this, so that any immediately sequential code blocks are turned in to tabs. You can [read more about ReadMe-flavored code blocks here](https://rdmd.readme.io/docs/code-blocks)!

**Comment by rafegoldberg** [comment]
To achieve the standard rendering you're expecting, you'd need to use proper markdown:

    ```
    Your code.
    ```

    ```
    More code.
    ```

Note the additional line break, which was missing from your initial examples.

**Comment by jrschumacher** [comment]
> A fenced code block may interrupt a paragraph, and **does not** require a blank line either before or after.

From [Common Mark](https://commonmark.org/) [v0.29 - 4.5 Fenced code blocks](https://spec.commonmark.org/0.29/#fenced-code-blocks)

According to ReadMe flavored code blocks, there is no indication that it requires blank lines and given it uses the CommonMark logo I would assume it should comply with the spec.

Additionally, the ReadMe flavored code block parser:
1. Find a code block
2. Look for ending code block
3. Find ending code block
4. See if next line is a code block
    1. If next line is code block; then is code block group
    2. ...

```
\```javascript tab-a
some code
\```
\```javascript tab-b
some code
\```

NOT

\```javascript tab-a
some code
\```javascript tab-b
some code
\```
```

**Comment by jrschumacher** [comment]
@rafegoldberg [Standard Markdown is CommonMark](https://blog.codinghorror.com/standard-markdown-is-now-common-markdown/)
