### ISSUE TITLE
Document supported code block languages

### ISSUE THREAD

**Issue by codycoggins-virtru** [readmeio/api-explorer#617]
1. To specify a language for a code block, please support the two letter abbreviations common in other markdown dialects (sh -> shell, js -> javascript, py ->python)
2. Most important, please document the languages you do support and the "info string" to use.

**Background:**
Our team ran into difficulty getting syntax highlighting working
(as in https://rdmd.readme.io/docs/code-blocks)

The issue was that readme flavored markdown was not recognizing our "info string" that specified the language for the code block.

Example:
```sh
echo "using keyword sh does not highlight code"
echo "Note that it works here in Github but not in readme.io"
```

```shell
echo "use shell so this will be highlighted"
```

Thanks!

**Comment by codycoggins-virtru** [comment]
One more observation - "c" is supported but "cpp" (C++) is not, in old or new markdown.  Is there a supported info string for C++?

**Comment by erunion** [comment]
For C++, you should be able to use `cplusplus`. Adding support for shortened versions of the language names is a great idea, and we'll get on that and documenting which ones we do support.

**Comment by rafegoldberg** [comment]
@codycoggins-virtru I agree with this in general. Unfortunately, we're currently using CodeMirror for syntax highlighting, which only supports [longform "language modes"](https://codemirror.net/mode/). For a number of other reasons (namely lagging SSR compatibility) we'll likely want to move away from CodeMirror in the future. But in the interim, we can probably work up a patchwork solution to remap these shorthands to their longform counterparts!

**Comment by codycoggins-virtru** [comment]
Thank you for having a look at this! Let us know if we at Virtru can do anything to help. And thanks for the tip on `cplusplus` - I tested and it works in both old and new markdown flavors.

**Comment by erunion** [comment]
I've added documentation on our supported languages, and their shortcodes, for syntax highlighting here: https://docs.readme.com/rdmd/docs/code-blocks#highlighting
