### ISSUE TITLE
Prefix RDMD generated anchors.

### ISSUE THREAD

**Issue by rafegoldberg** [readmeio/api-explorer#622]
ReadMe's magic blocks added a "section-" prefix to generated heading anchors; RDMD does not. We should (probably?) reapply this standard, as it is breaking in-page linking across various ReadMe projects.

**Comment by rafegoldberg** [comment]
Urgh, this is going to be unnecessarily annoying, since the [**`remark-slug`** plugin](https://github.com/remarkjs/remark-slug) we're using doesn't offer any configuration or customizations out of the box.

**Comment by darrenyong** [comment]
hey Rafe, just wanted to follow up on this issue. Are going to try to add the `section` back into the header, or are we going to leave it as is since you and Gabe mentioned it's more normalized?

**Comment by thephez** [comment]
Personally, I could handle the annoyance of updating all the heading links scattered through our projects if the result was that links were 100% github compatible (e.g no `section-` prefix, CamelCase items not split with hypens based on capitalization, etc.).
