### ISSUE TITLE
Using inline code syntax in callout titles only renders code

### ISSUE THREAD

**Issue by kanadgupta** [readmeio/api-explorer#652]
Writing something like this:

> 🚧 Make sure you're sending `postData` correctly!
> 
> According to the [HAR specification](http://www.softwareishard.com/blog/har-12-spec/#postData), a [`params` array](http://www.softwareishard.com/blog/har-12-spec/#params) should only be sent "in case of URL encoded parameters". So for JSON MIME types, [stringify the JSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) and send it as `postData.text`.
>
> If you have any questions, [please contact us](mailto:support@readme.io?subject=API%20Metrics%20Integrations)!

yields this (note the title):

![image](https://user-images.githubusercontent.com/8854718/80540768-8e4ce280-896f-11ea-9bb3-ebdd848d650c.png)

**Comment by rafegoldberg** [comment]
@kanadgupta I got a fix for this one in the works
