### ISSUE TITLE
Markdown heading anchor link compatibility issue

### ISSUE THREAD

**Issue by thephez** [readmeio/api-explorer#681]
# Description
For some reason the previous iteration of the markdown engine (the one being replaced) split CamelCase-ish headings by capital letter as well as space. For example:

Heading `GetAddressUtxos`'s link was `<page-url>#section-get-address-utxos` ([example page](https://dashcore.readme.io/docs/core-api-ref-remote-procedure-calls-address-index#section-get-address-utxos)).

The backwards compatibility feature added in the most recent iteration of the new engine does not appear to emulate that behavior. Links with a single cap (e.g. [Debug](https://dashcore.readme.io/docs/core-api-ref-remote-procedure-calls-control#section-debug)) worked properly with the new engine. But links such as the GetAddressUtxos one above simply drop the user at the top of the page rather than jumping to the correct section.

# Test links
Old format: 
https://dashcore.readme.io/docs/core-api-ref-remote-procedure-calls-address-index#section-get-address-utxos

New format: 
https://dashcore.readme.io/docs/core-api-ref-remote-procedure-calls-address-index#getaddressutxos

_Note: The reference project currently has the new engine disabled since it would have hundreds of broken links otherwise_

**Comment by rafegoldberg** [comment]
hey @thephez thanks for your detailed issue. Good catch on the camel casing; we also noticed it and released an address today in #687! This should be live on ReadMe by the end of the day.

**Comment by rafegoldberg** [comment]
**dope**: <img align=center src=https://user-images.githubusercontent.com/886627/81460036-a1be3180-9157-11ea-9bb8-255becafb467.png>

**Comment by thephez** [comment]
Thanks!
