### ISSUE TITLE
Don't start slugs with a `-`!

### ISSUE THREAD

**Issue by gkoberger** [readmeio/api-explorer#713]
If you start slugs with emojis, they get stripped from the slugs! However, the slug looks like `#-something`. Would it be possible to make it so that slugs never start with `-`?

Here's the header:
![image](https://user-images.githubusercontent.com/381393/83101699-c6773c00-a067-11ea-80b0-468dde2ef579.png)

And here's the slug it generates:

![image](https://user-images.githubusercontent.com/381393/83101707-cd9e4a00-a067-11ea-8562-cde5bfce72a8.png)

**Comment by rafegoldberg** [comment]
This anchor change is causing some issues with an upcoming migration we're planning; going to revert this this morning.
