### ISSUE TITLE
Markdown code block syntax recognition

### ISSUE THREAD

**Issue by thephez** [readmeio/api-explorer#723]
I noticed that code blocks that include a space between the ` ``` ` and the syntax name (e.g. ` ``` bash`) are not rendered with syntax highlighting. It would be nice if both ways were supported as they are on Github, StackEdit, etc..

This example page demos what I mean and links to a GH example also: https://dashcore-anchortest.readme.io/docs/markdown-code-blocks.

**Comment by rafegoldberg** [comment]
I hear ya on this type of convenience method, and indeed both GitHub and StackOverflow allow this; who knew! I think this is a valid point, so I'm going to leave this open and we'll definitely try to pull it in as we continue to improve the RDMD engine. (But I'd note that this _is_ [the standard markdown syntax](https://daringfireball.net/projects/markdown/), so this probably won't get our immediate attention. But we'll letchya know wrt/any updates here!)

**Comment by thephez** [comment]
Closing as it appears that the update is live (my example page is now rendering correctly anyway). Thanks!
