### ISSUE TITLE
Simple mode API snippet auth is being erroneously base64 encoded

### ISSUE THREAD

**Issue by erunion** [readmeio/api-explorer#832]
![Screen Shot 2020-07-14 at 10 07 47 AM](https://user-images.githubusercontent.com/33762/87455236-fe0b5a80-c5b9-11ea-8aa1-1855598dc34f.png)

Unclear if this a bug in the Explorer, `oas-to-har`, or `httpsnippet-client-api`, but `sdk.auth()` in this case should just be `sdk.auth('myapikey')`.

**Comment by gkoberger** [comment]
Is there something I can do to fix this? This is a pretty big one 😬  our API is completely broken now!

**Comment by erunion** [comment]
@gkoberger Yeah if you want to dig into it, by all means! I think the issue is in `packages/oas-to-har`, but I'm not sure.
