### ISSUE TITLE
Example reponse doesn't get rendered properly

### ISSUE THREAD

**Issue by mjcuva** [readmeio/api-explorer#90]
In build we have an example response here: https://github.com/readmeio/build-backend/blob/enhancement/files/api/logs.js#L108-L113

It seems like it gets run through codemirror, but just the raw html is printed.

![image](https://www.dropbox.com/s/ttqj1g4h1zs5728/Screenshot%202018-01-09%2015.01.13.png?raw=1)

**Comment by domharrington** [comment]
https://docs.readme.build/v1.0/reference#get_logs-users-service

**Comment by domharrington** [comment]
This is also a problem here: https://readmeio.github.io/api-explorer/?selected=swagger-files%2Fexamples.json
