### ISSUE TITLE
Ability to pre-populate parameters from JWT data

### ISSUE THREAD

**Issue by erunion** [readmeio/api-explorer#913]
We support passing variables from JWT objects into guides for having dynamic user-contextual information, but we unfortunately don't support doing this within the API Explorer and on parameters.

https://docs.readme.com/guides/docs/passing-data-to-jwt

**Comment by jordanmnunez** [comment]
Any news on when this would be worked on?

**Comment by erunion** [comment]
@jordanmnunez I don't unfortunately. It's in our backlog, but we're currently prioritizing some OAS support deficiencies.

**Comment by erunion** [comment]
Being handled with https://github.com/readmeio/api-explorer/pull/1189
